list = {
  'あ':   %w[a],
  'い':   %w[i yi],
  'う':   %w[u wu whu],
  'え':   %w[e],
  'お':   %w[o],
  'ぁ':   %w[la xa],
  'ぃ':   %w[li xi lyi xyi],
  'ぅ':   %w[lu xu],
  'ぇ':   %w[le xe lye xye],
  'ぉ':   %w[lo xo],
  'いぇ': %w[ye],
  'うぁ': %w[wha],
  'うぃ': %w[wi whi],
  'うぇ': %w[we whe],
  'うぉ': %w[who],
  'か':   %w[ka ca],
  'き':   %w[ki],
  'く':   %w[ku cu qu],
  'け':   %w[ke],
  'こ':   %w[ko co],
  'ヵ':   %w[lka xka],
  'ヶ':   %w[lke xke],
  'が':   %w[ga],
  'ぎ':   %w[gi],
  'ぐ':   %w[gu],
  'げ':   %w[ge],
  'ご':   %w[go],
  'きゃ': %w[kya],
  'きぃ': %w[kyi],
  'きゅ': %w[kyu],
  'きぇ': %w[kye],
  'きょ': %w[kyo],
  'ぎゃ': %w[gya],
  'ぎぃ': %w[gyi],
  'ぎゅ': %w[gyu],
  'ぎぇ': %w[gye],
  'ぎょ': %w[gyo],
  'くぁ': %w[qa kwa qwa],
  'くぃ': %w[qi qyi qwi],
  'くぅ': %w[qwu],
  'くぇ': %w[qe qye qwe],
  'くぉ': %w[qo qwo],
  'くゃ': %w[qya],
  'くゅ': %w[qyu],
  'くょ': %w[qyo],
  'ぐぁ': %w[gwa],
  'ぐぃ': %w[gwi],
  'ぐぅ': %w[gwu],
  'ぐぇ': %w[gwe],
  'ぐぉ': %w[gwo],
  'さ':   %w[sa],
  'し':   %w[si ci shi],
  'す':   %w[su],
  'せ':   %w[se ce],
  'そ':   %w[so],
  'ざ':   %w[za],
  'じ':   %w[zi ji],
  'ず':   %w[zu],
  'ぜ':   %w[ze],
  'ぞ':   %w[zo],
  'しゃ': %w[sya sha],
  'しぃ': %w[syi],
  'しゅ': %w[syu shu],
  'しぇ': %w[sye she],
  'しょ': %w[syo sho],
  'じゃ': %w[ja jya zya],
  'じぃ': %w[jyi zyi],
  'じゅ': %w[ju jyu zyu],
  'じぇ': %w[je jye zye],
  'じょ': %w[jo jyo zyo],
  'すぁ': %w[swa],
  'すぃ': %w[swi],
  'すぅ': %w[swu],
  'すぇ': %w[swe],
  'すぉ': %w[swo],
  'た':   %w[ta],
  'ち':   %w[ti chi],
  'つ':   %w[tu tsu],
  'て':   %w[te],
  'と':   %w[to],
  'っ':   %w[ltu xtu ltsu],
  'だ':   %w[da],
  'ぢ':   %w[di],
  'づ':   %w[du],
  'で':   %w[de],
  'ど':   %w[do],
  'ちゃ': %w[tya cha cya],
  'ちぃ': %w[tyi cyi],
  'ちゅ': %w[tyu chu cyu],
  'ちぇ': %w[tye che cye],
  'ちょ': %w[tyo cho cyo],
  'ぢゃ': %w[dya],
  'ぢぃ': %w[dyi],
  'ぢゅ': %w[dyu],
  'ぢぇ': %w[dye],
  'ぢょ': %w[dyo],
  'つぁ': %w[tsa],
  'つぃ': %w[tsi],
  'つぇ': %w[tse],
  'つぉ': %w[tso],
  'てゃ': %w[tha],
  'てぃ': %w[thi],
  'てゅ': %w[thu],
  'てぇ': %w[the],
  'てょ': %w[tho],
  'でゃ': %w[dha],
  'でぃ': %w[dhi],
  'でゅ': %w[dhu],
  'でぇ': %w[dhe],
  'でょ': %w[dho],
  'とぁ': %w[twa],
  'とぃ': %w[twi],
  'とぅ': %w[twu],
  'とぇ': %w[twe],
  'とぉ': %w[two],
  'どぁ': %w[dwa],
  'どぃ': %w[dwi],
  'どぅ': %w[dwu],
  'どぇ': %w[dwe],
  'どぉ': %w[dwo],
  'な':   %w[na],
  'に':   %w[ni],
  'ぬ':   %w[nu],
  'ね':   %w[ne],
  'の':   %w[no],
  'にゃ': %w[nya],
  'にぃ': %w[nyi],
  'にゅ': %w[nyu],
  'にぇ': %w[nye],
  'にょ': %w[nyo],
  'は':   %w[ha],
  'ひ':   %w[hi],
  'ふ':   %w[hu fu],
  'へ':   %w[he],
  'ほ':   %w[ho],
  'ば':   %w[ba],
  'び':   %w[bi],
  'ぶ':   %w[bu],
  'べ':   %w[be],
  'ぼ':   %w[bo],
  'ぱ':   %w[pa],
  'ぴ':   %w[pi],
  'ぷ':   %w[pu],
  'ぺ':   %w[pe],
  'ぽ':   %w[po],
  'ひゃ': %w[hya],
  'ひぃ': %w[hyi],
  'ひゅ': %w[hyu],
  'ひぇ': %w[hye],
  'ひょ': %w[hyo],
  'びゃ': %w[bya],
  'びぃ': %w[byi],
  'びゅ': %w[byu],
  'びぇ': %w[bye],
  'びょ': %w[byo],
  'ぴゃ': %w[pya],
  'ぴぃ': %w[pyi],
  'ぴゅ': %w[pyu],
  'ぴぇ': %w[pye],
  'ぴょ': %w[pyo],
  'ふぁ': %w[fa fwa],
  'ふぃ': %w[fi fyi fwi],
  'ふぅ': %w[fwu],
  'ふぇ': %w[fe fye fwe],
  'ふぉ': %w[fo fwo],
  'ふゃ': %w[fya],
  'ふゅ': %w[fyu],
  'ふょ': %w[fyo],
  'ヴぁ': %w[va],
  'ヴぃ': %w[vi vyi],
  'ヴ':   %w[vu],
  'ヴぇ': %w[ve vye],
  'ヴぉ': %w[vo],
  'ヴゃ': %w[vya],
  'ヴゅ': %w[vyu],
  'ヴょ': %w[vyo],
  'ま':   %w[ma],
  'み':   %w[mi],
  'む':   %w[mu],
  'め':   %w[me],
  'も':   %w[mo],
  'みゃ': %w[mya],
  'みぃ': %w[myi],
  'みゅ': %w[myu],
  'みぇ': %w[mye],
  'みょ': %w[myo],
  'や':   %w[ya],
  'ゆ':   %w[yu],
  'よ':   %w[yo],
  'ゃ':   %w[lya xya],
  'ゅ':   %w[lyu xyu],
  'ょ':   %w[lyo xyo],
  'ら':   %w[ra],
  'り':   %w[ri],
  'る':   %w[ru],
  'れ':   %w[re],
  'ろ':   %w[ro],
  'りゃ': %w[rya],
  'りぃ': %w[ryi],
  'りゅ': %w[ryu],
  'りぇ': %w[rye],
  'りょ': %w[ryo],
  'わ':   %w[wa],
  'を':   %w[wo],
  'ん':   %w[n nn n' xn],
  'ゎ':   %w[lwa xwa]
}
